[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "auto"

enableStaticServing = true

[theme]
base = "dark"
primaryColor = "#4B8BBE"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "warning"
